name: CVE Scanning for Maven

on:
  pull_request:
    paths:
      - 'pom.xml'
      - '.github/workflows/cve-scanning.yml'
  push:
    paths:
      - 'pom.xml'
      - '.github/workflows/cve-scanning.yml'
  schedule:
    # Run every day at 5am and 5pm
    - cron: '0 5,17 * * *'


jobs:
 depchecktest:
    runs-on: ubuntu-latest
    name: depcheck_test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn install 
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@1b5d19fd4a32ff0ff982e8c9d8e27dbf7ac8a46c
        id: Depcheck
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: 'spring-bot'
          format: 'HTML'
          path: '.'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --suppression ./.github/workflows/allow-list.xml
            --failOnCVSS 5
            --enableRetired
            
      - name: Upload Test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: Depcheck report
          path: ${{ github.workspace }}/reports
